### ISSUE TITLE
Porque esta usando o Venom-bot e WPPConnect?

### ISSUE THREAD

**Issue by devpremium** [AlanMartines/mywhats-api-node-venom#11]
Existe alguma vantagem em usar um ou outro ou é só para ter redundancia?

**Comment by devpremium** [comment]
Bacana, uma dica para você colocar no projeto seria colocar um wehook  para adicionar o link no .env e ele mandar tudo do onAck, onMessage para esse link

**Comment by AlanMartines** [comment]
Obrigado pela dica.
